version: '3.9'

services:
  streamlit_app:
    build:
      context: ./Streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./Streamlit:/app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: unless-stopped
